### ISSUE TITLE
Cannot detect anomaly with custom dataset

### ISSUE THREAD

**Issue by sajithdilshan** [twitter/AnomalyDetection#5]
I keep on getting below error when trying to detect anomaly with a custom data set which contains only a list of <timestamp, integer> list
```res = AnomalyDetectionTs(data, max_anoms=0.1, direction='both', plot=TRUE)
Error in detect_anoms(all_data[[i]], k = max_anoms, alpha = alpha, num_obs_per_period = period,  : 
  must supply period length for time series deomosition```

below is the first few lines of my data set
```
                     date   size
1     2014-11-09 03:39:31  19512
2     2014-11-09 03:42:20   5308
3     2014-11-09 03:46:14      0
4     2014-11-09 03:46:15   5270
5     2014-11-09 03:50:19    822
6     2014-11-09 03:52:58   5319
7     2014-11-09 03:53:23   5379
8     2014-11-09 03:53:23    266
9     2014-11-09 03:53:23     21
10    2014-11-09 03:53:23   7199
11    2014-11-09 03:53:23  15414
12    2014-11-09 03:53:23  95786
13    2014-11-09 03:53:24  12417
14    2014-11-09 03:53:26  29156
15    2014-11-09 03:53:27    462
16    2014-11-09 04:00:28      0
17    2014-11-09 04:00:29   5270
18    2014-11-09 04:01:54  51491
19    2014-11-09 04:02:05   5326
20    2014-11-09 04:06:10  47288
```

**Comment by owenvallis** [comment]
It seems like it isn't deriving the number of events per period from the data. I think this is because the method expects the input to be a dataframe instead of a list of lists. We'll add a check for that.

You can also pass in your 'size' column using AnomalyDetectionVec(), and then manually define your period length.

**Comment by sajithdilshan** [comment]
Got it. Thank you.

PS: There's a typo in the error message. I think it should be ``` time series decomposition```, not ```time series deomosition```

**Comment by jhochenbaum** [comment]
Thanks, that actually should have been fixed with a recent commit https://github.com/twitter/AnomalyDetection/commit/d8dcb7dacc4614af7739312100ca6a80e8134c17

**Comment by owenvallis** [comment]
Thanks for the heads up on the typo.

Also just noticed that the data timestamps seem to be at irregular intervals. The algorithm will work best with a regular sampling period for the data.

The data will still work using the AnomalyDetectionVec() function, but the seasonal decomposition might be slightly distorted due to the different sampling periods.
